language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
  - yarn lint
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: fuzzy-octo
  on:
    branch: master
    all_branches: false
    repo: joaaomanooel/fuzzy-octo
